### ISSUE TITLE
Active Cards Icon only shows correct value on hovering

### ISSUE THREAD

**Issue by talenelat-elin** [eustachi0/RemNoteThemes#2]
The active cards icon without any custom css active. (bottom right in the picture)
![image](https://user-images.githubusercontent.com/71895835/121290526-67980400-c904-11eb-92d7-006375643e4c.png)

The icon with your dark theme active
![image](https://user-images.githubusercontent.com/71895835/121290612-90b89480-c904-11eb-8687-d632668a0d37.png)

The icon when I hover over it.
![image](https://user-images.githubusercontent.com/71895835/121290698-b04fbd00-c904-11eb-826c-c51a8d526d6e.png)

**Comment by eustachi0** [comment]
Hi, thanks for reporting this. This is already fixed, you will see it in the next update this week.

**Comment by eustachi0** [comment]
This is fixed in the version 1.1 released 10 jun 2021
